<a href="https://colab.research.google.com/github/FatoniRahmat/Data-Analyst-in-Python/blob/main/Movie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Setup Environment & Run Packages

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

#Load Data

In [2]:
sheet_url = 'https://docs.google.com/spreadsheets/d/1bK36H8X5jgfDacwKDX9F3tNOaSm6s7aNAw44gIuWNzs/edit#gid=620735373'
sheet_url_trf = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')
df = pd.read_csv(sheet_url_trf)
pd.set_option('display.max_columns', None)
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,0,NaN,12.0,7.1,NaN,0

#Basic steps
1.Check Variable Names

2.Check Data Type

3.Handle Missing Values

4.Check Duplicate Records

##1. Check Variable Names
Column names provide a clear identification of the data contained within each column. By reviewing the column names, i can quickly understand the type of information stored in each column. This helps me make sense of the data and interpret it correctly.

In [3]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')


Now, we change the order of the columns:

In [4]:
col_order = ['movie_title', 'genres', 'color', 'duration', 'content_rating', 'title_year', 'language',
             'country', 'aspect_ratio', 'budget', 'gross', 'plot_keywords', 'movie_imdb_link',
             'imdb_score', 'num_voted_users', 'num_user_for_reviews', 'num_critic_for_reviews',
             'facenumber_in_poster', 'movie_facebook_likes', 'director_name', 'director_facebook_likes',
             'actor_1_name', 'actor_1_facebook_likes','actor_2_name', 'actor_2_facebook_likes',
             'actor_3_name', 'actor_3_facebook_likes', 'cast_total_facebook_likes']
df = df[col_order]
pd.set_option('display.max_columns', None)
df.head()

,movie_title,genres,color,duration,content_rating,title_year,language,country,aspect_ratio,budget,gross,plot_keywords,movie_imdb_link,imdb_score,num_voted_users,num_user_for_reviews,num_critic_for_reviews,facenumber_in_poster,movie_facebook_likes,director_name,director_facebook_likes,actor_1_name,actor_1_facebook_likes,actor_2_name,actor_2_facebook_likes,actor_3_name,actor_3_facebook_likes,cast_total_facebook_likes
0,Avatar,Action|Adventure|Fantasy|Sci-Fi,Color,178.0,PG-13,2009.0,English,USA,1.78,237000000,760505847.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,7.9,886204,3054.0,723.0,0.0,33000,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,936.0,Wes Studi,855.0,4834
1,Pirates of the Caribbean: At World's End,Action|Adventure|Fantasy,Color,169.0,PG-13,2007.0,English,USA,2.35,300000000,309404152.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,7.1,471220,1238.0,302.0,0.0,0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,5000.0,Jack Davenport,1000.0,48350
2,Spectre,Action|Adventure|Thriller,Color,148.0,PG-13,2015.0,English,UK,2.35,245000000,200074175.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,6.8,275868,994.0,602.0,1.0,85000,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,393.0,Stephanie Sigman,161.0,11700
3,The Dark Knight Rises,Action|Thriller,Color,164.0,PG-13,2012.0,English,USA,2.35,250000000,448130642.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,8.5,1144337,2701.0,813.0,0.0,164000,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,23000.0,Joseph Gordon-Levitt,23000.0,106759
4,Star Wars: Episode VII - The Force Awakens,Documentary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,7.1,8,NaN,NaN,0.0,0,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,12.0,NaN,NaN,143

##2. Check Data Type
Checking the data types is an important step in data cleaning because it helps ensure the consistency, accuracy, and reliability of the data.

In [5]:
df.dtypes

movie_title                   object
genres                        object
color                         object
duration                     float64
content_rating                object
title_year                   float64
language                      object
country                       object
aspect_ratio                 float64
budget                         int64
gross                        float64
plot_keywords                 object
movie_imdb_link               object
imdb_score                   float64
num_voted_users                int64
num_user_for_reviews         float64
num_critic_for_reviews       float64
facenumber_in_poster         float64
movie_facebook_likes           int64
director_name                 object
director_facebook_likes      float64
actor_1_name                  object
actor_1_facebook_likes       float64
actor_2_name                  object
actor_2_facebook_likes       float64
actor_3_name                  object
actor_3_facebook_likes       float64
cast_total_facebook_likes      int64
dtype: object

Based on data documentation, we must check whether the data type of variables is correct or not. The result shows, there is something wrong about duration, title_year, gross, num_user_for_reviews, num_critic_for_reviews, facenumber_in_poster, director_facebook_likes, actor_1_facebook_likes, actor_2_facebook_likes, actor_3_facebook_likes.

In [6]:
df['duration'] = df['duration'].astype('Int64')
df['title_year'] = df['title_year'].astype('object')
df['gross'] = df['gross'].astype('Int64')
df['num_user_for_reviews'] = df['num_user_for_reviews'].astype('Int64')
df['num_critic_for_reviews'] = df['num_critic_for_reviews'].astype('Int64')
df['facenumber_in_poster'] = df['facenumber_in_poster'].astype('Int64')
df['director_facebook_likes'] = df['director_facebook_likes'].astype('Int64')
df['actor_1_facebook_likes'] = df['actor_1_facebook_likes'].astype('Int64')
df['actor_2_facebook_likes'] = df['actor_2_facebook_likes'].astype('Int64')
df['actor_3_facebook_likes'] = df['actor_3_facebook_likes'].astype('Int64')
df.dtypes

movie_title                   object
genres                        object
color                         object
duration                       Int64
content_rating                object
title_year                    object
language                      object
country                       object
aspect_ratio                 float64
budget                         int64
gross                          Int64
plot_keywords                 object
movie_imdb_link               object
imdb_score                   float64
num_voted_users                int64
num_user_for_reviews           Int64
num_critic_for_reviews         Int64
facenumber_in_poster           Int64
movie_facebook_likes           int64
director_name                 object
director_facebook_likes        Int64
actor_1_name                  object
actor_1_facebook_likes         Int64
actor_2_name                  object
actor_2_facebook_likes         Int64
actor_3_name                  object
actor_3_facebook_likes         Int64
cast_total_facebook_likes      int64
dtype: object

##3. Handle Missing Values
Checking for missing values is an important step in data cleaning because missing values can have a significant impact on the quality and reliability of the data analysis. Missing values can lead to incomplete or inaccurate data, which can skew the analysis and produce misleading results. By identifying and handling missing values appropriately, me ensure the integrity and reliability of the data.

In [7]:
def nulls(df):
    null_values = pd.DataFrame(df.isnull().sum())
    null_values[1] = null_values[0] / len(df)
    null_values.columns = ['count','%pct']
    filtered_null = null_values[null_values['%pct'] > 0].sort_values(by='%pct', ascending=False)
    return filtered_null
nulls(df)

                         count      %pct
gross                      884  0.175292
aspect_ratio               329  0.065239
content_rating             303  0.060083
plot_keywords              153  0.030339
title_year                 108  0.021416
director_name              104  0.020623
director_facebook_likes    104  0.020623
num_critic_for_reviews      50  0.009915
actor_3_name                23  0.004561
actor_3_facebook_likes      23  0.004561
num_user_for_reviews        21  0.004164
color                       19  0.003768
duration                    15  0.002974
facenumber_in_poster        13  0.002578
actor_2_name                13  0.002578
actor_2_facebook_likes      13  0.002578
language                    12  0.002380
actor_1_name                 7  0.001388
actor_1_facebook_likes       7  0.001388
country                      5  0.000991

- Strategy One: Drop Column
The percentage of null value is more than 70%.

- Strategy Two: Drop Rows:
The percentage of null value is less than 5%.

- Strategy Three: Impute with Mode:
The percentage of null value is between 5% and 10%.
The datatype is categorical or lable

- Strategy Four: Impute with Mean or Median:
The percentage of null value is between 5% and 10%.
The datatype is numerical

- Strategy Five: Impute with KNN Method:
The percentage of null value is between 10% and 70%.
The datatype is categorical lable
They are not MNAR

- Strategy Six: Impute with KNN Method:
The percentage of null value is between 10% and 70%.
The datatype is Number
They are not MNAR

For NaN values of 17% such as gross, use the sixth strategy, for NaN values between 5% - 10%, such as aspect_ratio and content_rating, use strategies three and four. while for the rest who have NaN values below 5% use strategy two.
To solve the Missing Values case in the form of blank values in the gross column, for example the solution to be chosen is: each blank value will be replaced with 0.

In [8]:
#gross
df['gross'].fillna(0, inplace=True)

#aspect_ratio
value_mean = df['aspect_ratio'].mean()
df = df.fillna({'aspect_ratio': value_mean})

#content_rating
df['content_rating'] = df['content_rating'].fillna(df['content_rating'].mode()[0])

#the others
df = df.dropna(subset = ['plot_keywords', 'title_year', 'director_facebook_likes', 'director_name',
                         'num_critic_for_reviews', 'actor_3_name', 'actor_3_facebook_likes',
                         'num_user_for_reviews', 'color', 'duration', 'facenumber_in_poster',
                         'actor_2_name', 'actor_2_facebook_likes', 'language', 'actor_1_name',
                         'actor_1_facebook_likes', 'country'])

##4. Check Duplicate Rows
Duplicate rows can compromise the integrity of the dataset. If we have multiple identical rows, it can lead to inaccurate statistical analysis, misleading results, and duplicate entries in downstream processes. By identifying and removing duplicate rows, we ensure that the data accurately represents the underlying information.

In [9]:
df.duplicated().sum()

42

Because duplicate data comes from the aspect_ratio column, which is data that allows duplicate data to occur, so duplicate data is not deleted.

#Numbers


1.   Check Possible Range
2.   Sanity Check

##1. Check Possible Range
Checking the possible range is an important step in data cleaning because it helps identify and handle data values that fall outside the expected or valid range for a particular variable. By examining the range of values, we can identify outliers, data entry errors, or any other data points that are unlikely or impossible given the context of the data.

In [10]:
num_var = [col for col in df.columns if df[col].dtypes != 'O']
num_var

['duration',
 'aspect_ratio',
 'budget',
 'gross',
 'imdb_score',
 'num_voted_users',
 'num_user_for_reviews',
 'num_critic_for_reviews',
 'facenumber_in_poster',
 'movie_facebook_likes',
 'director_facebook_likes',
 'actor_1_facebook_likes',
 'actor_2_facebook_likes',
 'actor_3_facebook_likes',
 'cast_total_facebook_likes']

In [11]:
for i in range(len(num_var)):
    per = round((len(df[df[num_var[i]] < 0]) / len(df)) * 100, 5)
    print('{} | min {} | max {} | percentage %{}'.format(num_var[i], df[num_var[i]].min(), df[num_var[i]].max(), per))

duration | min 14 | max 330 | percentage %0.0
aspect_ratio | min 1.18 | max 16.0 | percentage %0.0
budget | min 0 | max 12215500000 | percentage %0.0
gross | min 0 | max 760505847 | percentage %0.0
imdb_score | min 1.6 | max 9.3 | percentage %0.0
num_voted_users | min 5 | max 1689764 | percentage %0.0
num_user_for_reviews | min 1 | max 5060 | percentage %0.0
num_critic_for_reviews | min 1 | max 813 | percentage %0.0
facenumber_in_poster | min 0 | max 43 | percentage %0.0
movie_facebook_likes | min 0 | max 349000 | percentage %0.0
director_facebook_likes | min 0 | max 23000 | percentage %0.0
actor_1_facebook_likes | min 0 | max 640000 | percentage %0.0
actor_2_facebook_likes | min 0 | max 137000 | percentage %0.0
actor_3_facebook_likes | min 0 | max 23000 | percentage %0.0
cast_total_facebook_likes | min 0 | max 656730 | percentage %0.0

We do not have any negative values.

##2. Sanity Check
Sanity checks can help ensure the consistency and integrity of the data. If two numerical variables are expected to have a certain relationship or dependency, a sanity check can help to understand. Among all numerical variables, first, we must realize there is a logical relationship between which variables. We should analye the relationship based on the data documentation.

- sanity 1 : actor_1_facebook_likes <= cast_total_facebook_likes
- sanity 2 : actor_2_facebook_likes <= cast_total_facebook_likes
- sanity 3 : actor_3_facebook_likes <= cast_total_facebook_likes

In [12]:
df['Sanity1'] = ['OK' if x <= y else 'NOT' for x, y in zip(df['actor_1_facebook_likes'], df['cast_total_facebook_likes'])]
df['Sanity2'] = ['OK' if x <= y else 'NOT' for x, y in zip(df['actor_2_facebook_likes'], df['cast_total_facebook_likes'])]
df['Sanity3'] = ['OK' if x <= y else 'NOT' for x, y in zip(df['actor_3_facebook_likes'], df['cast_total_facebook_likes'])]

In [13]:
df[df['Sanity1']=='NOT'].shape[0]
df[df['Sanity2']=='NOT'].shape[0]
df[df['Sanity3']=='NOT'].shape[0]

0

#String
1. Trimming and Transformation

##1. Trimming and Transformation
Text data often contains unwanted leading or trailing spaces, which can affect data integrity and analysis. Trimming these spaces ensures consistency and accuracy in subsequent operations.

In [14]:
df[['movie_title','genres','color','language', 'plot_keywords', 'director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name' ]] = df[['movie_title','genres','color','language', 'plot_keywords', 'director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name' ]].applymap(str.strip).applymap(str.upper)

#Adding Columns

Adding a category duration column, this is only optional.

In [20]:
def category_duration(duration):
    if (duration<90):
      return 'Category_1'
    elif ((duration>=90) and (duration<=120)):
      return 'Category_2'
    else:
      return 'Category_3'

In [21]:
df['movie_duration_category'] = df['duration'].apply(category_duration)
df_view = df[['movie_title', 'duration', 'movie_duration_category']]
df_view

,movie_title,duration,movie_duration_category
0,AVATAR,178,Category_3
1,PIRATES OF THE CARIBBEAN: AT WORLD'S END,169,Category_3
2,SPECTRE,148,Category_3
3,THE DARK KNIGHT RISES,164,Category_3
5,JOHN CARTER,132,Category_3
...,...,...,...
5034,CAVITE,80,Category_1
5035,EL MARIACHI,81,Category_1
5037,NEWLYWEDS,95,Category_2
5038,SIGNED SEALED DELIVERED,87,Category_1
5042,MY DATE WITH DREW,90,Category_2

#Export the File
First, we remove the Sanity column that we made it before, and then export the cleaned data.

In [17]:
df = df.drop(['Sanity1'], axis=1)
df = df.drop(['Sanity2'], axis=1)
df = df.drop(['Sanity3'], axis=1)
df

,movie_title,genres,color,duration,content_rating,title_year,language,country,aspect_ratio,budget,gross,plot_keywords,movie_imdb_link,imdb_score,num_voted_users,num_user_for_reviews,num_critic_for_reviews,facenumber_in_poster,movie_facebook_likes,director_name,director_facebook_likes,actor_1_name,actor_1_facebook_likes,actor_2_name,actor_2_facebook_likes,actor_3_name,actor_3_facebook_likes,cast_total_facebook_likes,movie_duration_category
0,AVATAR,ACTION|ADVENTURE|FANTASY|SCI-FI,COLOR,178,PG-13,2009.0,ENGLISH,USA,1.780000,237000000,760505847,AVATAR|FUTURE|MARINE|NATIVE|PARAPLEGIC,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,7.9,886204,3054,723,0,33000,JAMES CAMERON,0,CCH POUNDER,1000,JOEL DAVID MOORE,936,WES STUDI,855,4834,Category_3
1,PIRATES OF THE CARIBBEAN: AT WORLD'S END,ACTION|ADVENTURE|FANTASY,COLOR,169,PG-13,2007.0,ENGLISH,USA,2.350000,300000000,309404152,GODDESS|MARRIAGE CEREMONY|MARRIAGE PROPOSAL|PI...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,7.1,471220,1238,302,0,0,GORE VERBINSKI,563,JOHNNY DEPP,40000,ORLANDO BLOOM,5000,JACK DAVENPORT,1000,48350,Category_3
2,SPECTRE,ACTION|ADVENTURE|THRILLER,COLOR,148,PG-13,2015.0,ENGLISH,UK,2.350000,245000000,200074175,BOMB|ESPIONAGE|SEQUEL|SPY|TERRORIST,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,6.8,275868,994,602,1,85000,SAM MENDES,0,CHRISTOPH WALTZ,11000,RORY KINNEAR,393,STEPHANIE SIGMAN,161,11700,Category_3
3,THE DARK KNIGHT RISES,ACTION|THRILLER,COLOR,164,PG-13,2012.0,ENGLISH,USA,2.350000,250000000,448130642,DECEPTION|IMPRISONMENT|LAWLESSNESS|POLICE OFFI...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,8.5,1144337,2701,813,0,164000,CHRISTOPHER NOLAN,22000,TOM HARDY,27000,CHRISTIAN BALE,23000,JOSEPH GORDON-LEVITT,23000,106759,Category_3
5,JOHN CARTER,ACTION|ADVENTURE|SCI-FI,COLOR,132,PG-13,2012.0,ENGLISH,USA,2.350000,263700000,73058679,ALIEN|AMERICAN CIVIL WAR|MALE NIPPLE|MARS|PRIN...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,6.6,212204,738,462,1,24000,ANDREW STANTON,475,DARYL SABARA,640,SAMANTHA MORTON,632,POLLY WALKER,530,1873,Category_3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5034,CAVITE,THRILLER,COLOR,80,Not Rated,2005.0,ENGLISH,Philippines,2.220403,7000,70071,JIHAD|MINDANAO|PHILIPPINES|SECURITY GUARD|SQUA...,http://www.imdb.com/title/tt0428303/?ref_=fn_t...,6.3,589,35,35,0,74,NEILL DELA LLANA,0,IAN GAMAZON,0,EDGAR TANCANGCO,0,QUYNN TON,0,0,Category_1
5035,EL MARIACHI,ACTION|CRIME|DRAMA|ROMANCE|THRILLER,COLOR,81,R,1992.0,SPANISH,USA,1.370000,7000,2040920,ASSASSIN|DEATH|GUITAR|GUN|MARIACHI,http://www.imdb.com/title/tt0104815/?ref_=fn_t...,6.9,52055,130,56,0,0,ROBERT RODRIGUEZ,0,CARLOS GALLARDO,121,PETER MARQUARDT,20,CONSUELO GÓMEZ,6,147,Category_1
5037,NEWLYWEDS,COMEDY|DRAMA,COLOR,95,Not Rated,2011.0,ENGLISH,USA,2.220403,9000,4584,WRITTEN AND DIRECTED BY CAST MEMBER,http://www.imdb.com/title/tt1880418/?ref_=fn_t...,6.4,1338,14,14,1,413,EDWARD BURNS,0,KERRY BISHÉ,296,CAITLIN FITZGERALD,205,DANIELLA PINEDA,133,690,Category_2
5038,SIGNED SEALED DELIVERED,COMEDY|DRAMA,COLOR,87,R,2013.0,ENGLISH,Canada,2.220403,0,0,FRAUD|POSTAL WORKER|PRISON|THEFT|TRIAL,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,7.7,629,6,1,2,84,SCOTT SMITH,2,ERIC MABIUS,637,DAPHNE ZUNIGA,470,CRYSTAL LOWE,318,2283,Category_1
5042,MY DATE WITH DREW,DOCUMENTARY,COLOR,90,PG,2004.0,ENGLISH,USA,1.850000,1100,85222,ACTRESS NAME IN TITLE|CRUSH|DATE|FOUR WORD TIT...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,6.6,4285,84,43,0,456,JON GUNN,16,JOHN AUGUST,86,BRIAN HERZLINGER,23,JON GUNN,16,163,Category_2

In [18]:
df.to_csv('Movie_Dataset_Cleaned.csv')