<a href="https://colab.research.google.com/github/FatoniRahmat/Data-Analyst-in-Python/blob/main/Movie_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Setup Environment & Run Packages

In [107]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

#Load Data

In [109]:
#import dataset
sheet_url = 'https://docs.google.com/spreadsheets/d/1bK36H8X5jgfDacwKDX9F3tNOaSm6s7aNAw44gIuWNzs/edit#gid=620735373'
sheet_url_trf = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')
df = pd.read_csv(sheet_url_trf)
pd.set_option('display.max_columns', None)
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,0,NaN,12.0,7.1,NaN,0

#Basic steps
1.Check Variable Names

2.Check Data Type

3.Handle Missing Values

4.Check Duplicate Records

##1. Check Variable Names
Column names provide a clear identification of the data contained within each column. By reviewing the column names, i can quickly understand the type of information stored in each column. This helps me make sense of the data and interpret it correctly.

In [110]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')


Now, we change the order of the columns:

In [129]:
col_order = ['movie_title', 'genres', 'color', 'duration', 'content_rating', 'title_year', 'language',
             'country', 'aspect_ratio', 'budget', 'gross', 'plot_keywords', 'movie_imdb_link',
             'imdb_score', 'num_voted_users', 'num_user_for_reviews', 'num_critic_for_reviews',
             'facenumber_in_poster', 'movie_facebook_likes', 'director_name', 'director_facebook_likes',
             'actor_1_name', 'actor_1_facebook_likes','actor_2_name', 'actor_2_facebook_likes',
             'actor_3_name', 'actor_3_facebook_likes', 'cast_total_facebook_likes']
df = df[col_order]
pd.set_option('display.max_columns', None)
df

,movie_title,genres,color,duration,content_rating,title_year,language,country,aspect_ratio,budget,gross,plot_keywords,movie_imdb_link,imdb_score,num_voted_users,num_user_for_reviews,num_critic_for_reviews,facenumber_in_poster,movie_facebook_likes,director_name,director_facebook_likes,actor_1_name,actor_1_facebook_likes,actor_2_name,actor_2_facebook_likes,actor_3_name,actor_3_facebook_likes,cast_total_facebook_likes
0,396.0,106.0,1.0,178.0,7.0,83.0,11.0,62.0,1.780,237000000.0,760505847.0,1318.0,2964.0,7.9,886204.0,3054.0,723.0,0.0,33000.0,922.0,0.0,264.0,1000.0,1405.0,936.0,3437.0,855.0,4834.0
1,2725.0,100.0,1.0,169.0,7.0,81.0,11.0,62.0,2.350,300000000.0,309404152.0,4281.0,2720.0,7.1,471220.0,1238.0,302.0,0.0,0.0,794.0,563.0,976.0,40000.0,2216.0,5000.0,1390.0,1000.0,48350.0
2,3274.0,127.0,1.0,148.0,7.0,89.0,11.0,61.0,2.350,245000000.0,200074175.0,2078.0,4532.0,6.8,275868.0,994.0,602.0,1.0,85000.0,2021.0,0.0,349.0,11000.0,2487.0,393.0,3129.0,161.0,11700.0
3,3705.0,287.0,1.0,164.0,7.0,86.0,11.0,62.0,2.350,250000000.0,448130642.0,3482.0,3755.0,8.5,1144337.0,2701.0,813.0,0.0,164000.0,373.0,22000.0,1963.0,27000.0,532.0,23000.0,1763.0,23000.0,106759.0
4,3327.0,753.0,2.0,116.8,18.0,91.0,47.0,65.0,2.146,0.0,213349.2,4760.0,4917.0,7.1,8.0,5.8,10.4,0.0,0.0,600.0,131.0,522.0,131.0,2431.0,12.0,3521.0,58.2,143.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,3160.0,605.0,1.0,87.0,18.0,87.0,11.0,10.0,4.880,0.0,26285.8,4138.0,4695.0,7.7,629.0,6.0,1.0,2.0,84.0,2047.0,2.0,594.0,637.0,671.0,470.0,705.0,318.0,2283.0
5039,3785.0,735.0,1.0,43.0,10.0,91.0,11.0,62.0,16.000,0.0,28346720.0,3339.0,4370.0,7.5,73839.0,359.0,43.0,1.0,32000.0,2398.0,199.0,1445.0,841.0,2904.0,593.0,2973.0,319.0,1753.0
5040,133.0,823.0,1.0,76.0,18.0,87.0,11.0,62.0,2.350,1400.0,170192.4,4760.0,4396.0,6.3,38.0,3.0,13.0,0.0,16.0,186.0,0.0,612.0,0.0,1972.0,0.0,798.0,0.0,0.0
5041,3107.0,638.0,1.0,100.0,7.0,86.0,11.0,62.0,2.350,0.0,10443.0,4760.0,4368.0,6.3,1255.0,9.0,14.0,5.0,660.0,453.0,0.0,31.0,946.0,649.0,719.0,1004.0,489.0,2386.0
5042,2458.0,753.0,1.0,90.0,6.0,78.0,11.0,62.0,1.850,1100.0,85222.0,402.0,2341.0,6.6,4285.0,84.0,43.0,0.0,456.0,1158.0,16.0,947.0,86.0,378.0,23.0,1732.0,16.0,163.0

##2. Check Data Type
Checking the data types is an important step in data cleaning because it helps ensure the consistency, accuracy, and reliability of the data.

In [112]:
df.dtypes

movie_title                   object
genres                        object
color                         object
duration                     float64
content_rating                object
title_year                   float64
language                      object
country                       object
aspect_ratio                 float64
budget                         int64
gross                        float64
plot_keywords                 object
movie_imdb_link               object
imdb_score                   float64
num_voted_users                int64
num_user_for_reviews         float64
num_critic_for_reviews       float64
facenumber_in_poster         float64
movie_facebook_likes           int64
director_name                 object
director_facebook_likes      float64
actor_1_name                  object
actor_1_facebook_likes       float64
actor_2_name                  object
actor_2_facebook_likes       float64
actor_3_name                  object
actor_3_facebook_likes       float64
cast_total_facebook_likes      int64
dtype: object

Based on data documentation, we must check whether the data type of variables is correct or not. The result shows, there is something wrong about duration, title_year, gross, num_user_for_reviews, num_critic_for_reviews, facenumber_in_poster, director_facebook_likes, actor_1_facebook_likes, actor_2_facebook_likes, actor_3_facebook_likes.

In [113]:
df['duration'] = df['duration'].astype('Int64')
df['title_year'] = df['title_year'].astype('object')
df['gross'] = df['gross'].astype('Int64')
df['num_user_for_reviews'] = df['num_user_for_reviews'].astype('Int64')
df['num_critic_for_reviews'] = df['num_critic_for_reviews'].astype('Int64')
df['facenumber_in_poster'] = df['facenumber_in_poster'].astype('Int64')
df['director_facebook_likes'] = df['director_facebook_likes'].astype('Int64')
df['actor_1_facebook_likes'] = df['actor_1_facebook_likes'].astype('Int64')
df['actor_2_facebook_likes'] = df['actor_2_facebook_likes'].astype('Int64')
df['actor_3_facebook_likes'] = df['actor_3_facebook_likes'].astype('Int64')
df.dtypes

movie_title                   object
genres                        object
color                         object
duration                       Int64
content_rating                object
title_year                    object
language                      object
country                       object
aspect_ratio                 float64
budget                         int64
gross                          Int64
plot_keywords                 object
movie_imdb_link               object
imdb_score                   float64
num_voted_users                int64
num_user_for_reviews           Int64
num_critic_for_reviews         Int64
facenumber_in_poster           Int64
movie_facebook_likes           int64
director_name                 object
director_facebook_likes        Int64
actor_1_name                  object
actor_1_facebook_likes         Int64
actor_2_name                  object
actor_2_facebook_likes         Int64
actor_3_name                  object
actor_3_facebook_likes         Int64
cast_total_facebook_likes      int64
dtype: object

##3. Handle Missing Values
Checking for missing values is an important step in data cleaning because missing values can have a significant impact on the quality and reliability of the data analysis. Missing values can lead to incomplete or inaccurate data, which can skew the analysis and produce misleading results. By identifying and handling missing values appropriately, me ensure the integrity and reliability of the data.

In [119]:
def nulls(df):
    null_values = pd.DataFrame(df.isnull().sum())
    null_values[1] = null_values[0] / len(df)
    null_values.columns = ['count','%pct']
    filtered_null = null_values[null_values['%pct'] > 0].sort_values(by='%pct', ascending=False)
    return filtered_null
nulls(df)

                         count      %pct
gross                      884  0.175292
aspect_ratio               329  0.065239
content_rating             303  0.060083
plot_keywords              153  0.030339
title_year                 108  0.021416
director_name              104  0.020623
director_facebook_likes    104  0.020623
num_critic_for_reviews      50  0.009915
actor_3_name                23  0.004561
actor_3_facebook_likes      23  0.004561
num_user_for_reviews        21  0.004164
color                       19  0.003768
duration                    15  0.002974
facenumber_in_poster        13  0.002578
actor_2_name                13  0.002578
actor_2_facebook_likes      13  0.002578
language                    12  0.002380
actor_1_name                 7  0.001388
actor_1_facebook_likes       7  0.001388
country                      5  0.000991

- Strategy One: Drop Column
The percentage of null value is more than 70%.

- Strategy Two: Drop Rows:
The percentage of null value is less than 5%.

- Strategy Three: Impute with Mode:
The percentage of null value is between 5% and 10%.
The datatype is categorical or lable

- Strategy Four: Impute with Mean or Median:
The percentage of null value is between 5% and 10%.
The datatype is numerical

- Strategy Five: Impute with KNN Method:
The percentage of null value is between 10% and 70%.
The datatype is categorical lable
They are not MNAR

- Strategy Six: Impute with KNN Method:
The percentage of null value is between 10% and 70%.
The datatype is Number
They are not MNAR

for NaN values of 17% such as gross, use the sixth strategy, for NaN values between 5% - 10%, such as aspect_ratio and content_rating, use strategies three and four. while for the rest who have NaN values below 5% use strategy two.

In [120]:
#transformasi (encoding)
from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()
df['movie_title'] = encode.fit_transform(df['movie_title'].values)
df['genres'] = encode.fit_transform(df['genres'].values)
df['content_rating'] = encode.fit_transform(df['content_rating'].values)
df['title_year'] = encode.fit_transform(df['title_year'].values)
df['language'] = encode.fit_transform(df['language'].values)
df['country'] = encode.fit_transform(df['country'].values)
df['color'] = encode.fit_transform(df['color'].values)
df['plot_keywords'] = encode.fit_transform(df['plot_keywords'].values)
df['movie_imdb_link'] = encode.fit_transform(df['movie_imdb_link'].values)
df['director_name'] = encode.fit_transform(df['director_name'].values)
df['actor_1_name'] = encode.fit_transform(df['actor_1_name'].values)
df['actor_2_name'] = encode.fit_transform(df['actor_2_name'].values)
df['actor_3_name'] = encode.fit_transform(df['actor_3_name'].values)
df.head()

,movie_title,genres,color,duration,content_rating,title_year,language,country,aspect_ratio,budget,gross,plot_keywords,movie_imdb_link,imdb_score,num_voted_users,num_user_for_reviews,num_critic_for_reviews,facenumber_in_poster,movie_facebook_likes,director_name,director_facebook_likes,actor_1_name,actor_1_facebook_likes,actor_2_name,actor_2_facebook_likes,actor_3_name,actor_3_facebook_likes,cast_total_facebook_likes
0,396,106,1,178,7,83,11,62,1.78,237000000,760505847,1318,2964,7.9,886204,3054,723,0,33000,922,0,264,1000,1405,936,3437,855,4834
1,2725,100,1,169,7,81,11,62,2.35,300000000,309404152,4281,2720,7.1,471220,1238,302,0,0,794,563,976,40000,2216,5000,1390,1000,48350
2,3274,127,1,148,7,89,11,61,2.35,245000000,200074175,2078,4532,6.8,275868,994,602,1,85000,2021,0,349,11000,2487,393,3129,161,11700
3,3705,287,1,164,7,86,11,62,2.35,250000000,448130642,3482,3755,8.5,1144337,2701,813,0,164000,373,22000,1963,27000,532,23000,1763,23000,106759
4,3327,753,2,<NA>,18,91,47,65,NaN,0,<NA>,4760,4917,7.1,8,<NA>,<NA>,0,0,600,131,522,131,2431,12,3521,<NA>,143

In [121]:
#gross
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
df = pd.DataFrame(imputer.fit_transform(df),columns = df.columns)

#aspect_ratio
value_mean = df['aspect_ratio'].mean()
df = df.fillna({'aspect_ratio': value_mean})

#content_rating
df['content_rating'] = df['content_rating'].fillna(df['content_rating'].mode()[0])

#the others
df = df.dropna(subset = ['plot_keywords', 'title_year', 'director_facebook_likes', 'director_name',
                         'num_critic_for_reviews', 'actor_3_name', 'actor_3_facebook_likes',
                         'num_user_for_reviews', 'color', 'duration', 'facenumber_in_poster',
                         'actor_2_name', 'actor_2_facebook_likes', 'language', 'actor_1_name',
                         'actor_1_facebook_likes', 'country'])

In [123]:
df.isna().sum()

movie_title                  0
genres                       0
color                        0
duration                     0
content_rating               0
title_year                   0
language                     0
country                      0
aspect_ratio                 0
budget                       0
gross                        0
plot_keywords                0
movie_imdb_link              0
imdb_score                   0
num_voted_users              0
num_user_for_reviews         0
num_critic_for_reviews       0
facenumber_in_poster         0
movie_facebook_likes         0
director_name                0
director_facebook_likes      0
actor_1_name                 0
actor_1_facebook_likes       0
actor_2_name                 0
actor_2_facebook_likes       0
actor_3_name                 0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
dtype: int64

##4. Check Duplicate Rows
Duplicate rows can compromise the integrity of the dataset. If we have multiple identical rows, it can lead to inaccurate statistical analysis, misleading results, and duplicate entries in downstream processes. By identifying and removing duplicate rows, we ensure that the data accurately represents the underlying information.

In [124]:
df.duplicated().sum()

45

This dataset is a dataset that allows for duplicate data, so duplicate data is not removed.

#Numbers


1.   Check Possible Range

##1. Check Possible Range
Checking the possible range is an important step in data cleaning because it helps identify and handle data values that fall outside the expected or valid range for a particular variable. By examining the range of values, we can identify outliers, data entry errors, or any other data points that are unlikely or impossible given the context of the data.

In [125]:
num_var = [col for col in df.columns if df[col].dtypes != 'O']
num_var

['movie_title',
 'genres',
 'color',
 'duration',
 'content_rating',
 'title_year',
 'language',
 'country',
 'aspect_ratio',
 'budget',
 'gross',
 'plot_keywords',
 'movie_imdb_link',
 'imdb_score',
 'num_voted_users',
 'num_user_for_reviews',
 'num_critic_for_reviews',
 'facenumber_in_poster',
 'movie_facebook_likes',
 'director_name',
 'director_facebook_likes',
 'actor_1_name',
 'actor_1_facebook_likes',
 'actor_2_name',
 'actor_2_facebook_likes',
 'actor_3_name',
 'actor_3_facebook_likes',
 'cast_total_facebook_likes']

In [127]:
for i in range(len(num_var)):
    per = round((len(df[df[num_var[i]] < 0]) / len(df)) * 100, 5)
    print('{} | min {} | max {} | percentage %{}'.format(num_var[i], df[num_var[i]].min(), df[num_var[i]].max(), per))

movie_title | min 0.0 | max 4915.0 | percentage %0.0
genres | min 0.0 | max 913.0 | percentage %0.0
color | min 0.0 | max 2.0 | percentage %0.0
duration | min 7.0 | max 511.0 | percentage %0.0
content_rating | min 0.0 | max 18.0 | percentage %0.0
title_year | min 0.0 | max 91.0 | percentage %0.0
language | min 0.0 | max 47.0 | percentage %0.0
country | min 0.0 | max 65.0 | percentage %0.0
aspect_ratio | min 1.18 | max 16.0 | percentage %0.0
budget | min 0.0 | max 12215500000.0 | percentage %0.0
gross | min 162.0 | max 760505847.0 | percentage %0.0
plot_keywords | min 0.0 | max 4760.0 | percentage %0.0
movie_imdb_link | min 0.0 | max 4918.0 | percentage %0.0
imdb_score | min 1.6 | max 9.5 | percentage %0.0
num_voted_users | min 5.0 | max 1689764.0 | percentage %0.0
num_user_for_reviews | min 1.0 | max 5060.0 | percentage %0.0
num_critic_for_reviews | min 1.0 | max 813.0 | percentage %0.0
facenumber_in_poster | min 0.0 | max 43.0 | percentage %0.0
movie_facebook_likes | min 0.0 | max 349000.0 | percentage %0.0
director_name | min 0.0 | max 2398.0 | percentage %0.0
director_facebook_likes | min 0.0 | max 23000.0 | percentage %0.0
actor_1_name | min 0.0 | max 2097.0 | percentage %0.0
actor_1_facebook_likes | min 0.0 | max 640000.0 | percentage %0.0
actor_2_name | min 0.0 | max 3032.0 | percentage %0.0
actor_2_facebook_likes | min 0.0 | max 137000.0 | percentage %0.0
actor_3_name | min 0.0 | max 3521.0 | percentage %0.0
actor_3_facebook_likes | min 0.0 | max 23000.0 | percentage %0.0
cast_total_facebook_likes | min 0.0 | max 656730.0 | percentage %0.0

We do not have any negative values.

#Adding Columns

In [164]:
#Add a column with conditions
def category_duration(duration):
    if (duration<90):
      return 'Category_1'
    elif ((duration>=90) and (duration<=120)):
      return 'Category_2'
    else:
      return 'Category_3'

In [165]:
#create columns
df['movie_duration_category'] = df['duration'].apply(category_duration)
df_view = df[['movie_title', 'duration', 'movie_duration_category']]
df_view

      movie_title  duration movie_duration_category
0           396.0     178.0              Category_3
1          2725.0     169.0              Category_3
2          3274.0     148.0              Category_3
3          3705.0     164.0              Category_3
4          3327.0     116.8              Category_2
...           ...       ...                     ...
5038       3160.0      87.0              Category_1
5039       3785.0      43.0              Category_1
5040        133.0      76.0              Category_1
5041       3107.0     100.0              Category_2
5042       2458.0      90.0              Category_2

[5043 rows x 3 columns]

#Export the File

In [171]:
df.to_csv('Movie_Dataset_Cleaned.csv')